---
- hosts: webservers
  become: true
  tasks:
  - name: Create multiple directories
  file: path={{item}} state=directory
  with_items:
  - '/home/ansible/vn1'
  - '/home/ansible/vn2'
  - '/home/ansible/vn3'
=======================================
 Create multiple directories.
 To create multiple directories with one single task you can use the loop with_items statement. 
So when you run the below playbook it is interpreted as 3 different tasks.

