Archive or ZIP files and Folders

Using the Ansible archive module you can compress files or folders to ‘zip’, ‘.gz’, or ‘bz2’ format.

Note: The files or folders to be compressed should be available on the target servers and should have the packages for tar, bzip2, gzip, zip file installed on them. You can have a separate playbook task for installing these packages.

---
- hosts: all
  become: true
  tasks:
  - name: Ansible zip file example
    archive:
     path: /home/ansible/rakesh.txt
     dest: /home/ansible/rakesh.zip
     format: zip
The above playbook will zip the file niranjan.txt to niranjan.zip file

---
- hosts: all
  tasks:
  - name: Ansible zip multiple files example
  archive:
   path:
    - /home/ansible/rakesh.txt
    - /home/ansible/rakesh.txt
   dest: /home/ansible/rakesh.zip
   format: zip
The above playbook will zip multiple files to niranjan.zip file.

- hosts: all
  tasks:
  - name: Ansible zip directory example
    archive:
     path:
      - /home/ansible
     dest: /home/ansible/rakesh.zip
     format: zip
The above playbook will zip all files in the /home/ansible directory.
==============
